[package]
name = "syncthreads"
version = "0.1.0"
edition = "2024"

[dependencies]
atomic-wait = "1.1.0"
num_cpus = "1.16.0"
rayon = "1.10.0"

[dev-dependencies]
aligned-vec = "0.6.2"
diol = { version = "0.8.3", default-features = false }
rayon = "1.10.0"
